from pathlib import Path
import shutil
from datetime import datetime

"""
  Generates a SystemVerilog header file containing image and AXI-Stream parameters.
    
  This function creates a `.svh` file with `include` guards. If the file already exists,
  a backup is created before overwriting to prevent accidental data loss.

  Args:
    fileName (str): Path and name of the .svh file to generate.
    img_height (int): The height of the image in pixels.
    img_width (int): The width of the image in pixels.
    axis_tdata_width (int, optional): Bit width of the AXI-Stream TDATA signal. Defaults to 8.
    axis_tuser_width (int, optional): Bit width of the AXI-Stream TUSER signal. Defaults to 1.

  Returns:
    None
"""
def generate_hdl_params(fileName: str,
                        img_height: int,
                        img_width: int,
                        axis_tdata_width: int = 8,
                        axis_tuser_width: int = 1):

  output_file = Path(fileName)
  output_file.parent.mkdir(parents=True, exist_ok=True)

  backup_file = output_file.with_suffix(output_file.suffix + ".backup")

  if output_file.exists():
    shutil.copy(output_file, backup_file)
    print(f"[INFO] Backup created: {backup_file}")

  content = f"""\
// Auto-generated by Python
// Generated on: {datetime.now().isoformat()}
`ifndef __PARAMETERS_SVH__
`define __PARAMETERS_SVH__

`define IMG_HEIGHT {img_height}
`define IMG_WIDTH {img_width}

`define AXIS_TDATA_WIDTH {axis_tdata_width}
`define AXIS_TUSER_WIDTH {axis_tuser_width}

`endif
  """

  output_file.write_text(content)
  print(f"[OK] Generated {output_file}")