import numpy as np
from pathlib import Path

"""
  Flattens a 2D image array and saves it as a text file for HDL testbench input.

  Args:
    image (np.ndarray): The 2D image array to export.
    path (str): Output text file path.
"""
def image_to_txt(image: np.ndarray, path: str):
  output_file = Path(path)
  output_file.parent.mkdir(parents=True, exist_ok=True)
  with open(path, "w") as f:
    for pix in image.flatten():
      f.write(f"{int(pix)}\n")

"""
  Reconstructs an image from a text file generated by an HDL simulation output.

  Note:
    The reconstruction logic accounts for the typical 'border loss'
    (e.g., 3x3 convolution results in a slightly smaller output image).

  Args:
    path (str): Path to the simulation output text file.
    height (int): Original image height.
    width (int): Original image width.

  Returns:
    np.ndarray: The reconstructed image array, clipped to 0-255.
"""
def txt_to_image(path: str, height: int, width:int):
  output_file = Path(path)
  output_file.parent.mkdir(parents=True, exist_ok=True)
  with open(path, "r") as f:
    data = [int(line.strip()) for line in f if line.strip()]

  img = np.zeros((height-2, width-3),dtype=np.int32)
  idx = 0
  for i in range(0, height-2):
      for j in range(0, width-3):
          if idx >= len(data):
              print("Ran out of FPGA data at idx =", idx)
              return
          img[i,j] = min(max(data[idx], 0), 255)
          idx += 1
  return img