// Auto-generated by Python
// Generated on: 2026-02-08T14:00:51.768793
`ifndef __PARAMETERS_SVH__
`define __PARAMETERS_SVH__

`define IMG_HEIGHT 300
`define IMG_WIDTH 332

`define AXIS_TDATA_WIDTH 8
`define AXIS_TUSER_WIDTH 1

`endif
  