// Auto-generated by Python
// Generated on: 2026-02-21T00:00:50.231110
`ifndef __PARAMETERS_SVH__
`define __PARAMETERS_SVH__

`define IMG_HEIGHT 178
`define IMG_WIDTH 178

`define AXIS_TDATA_WIDTH 8
`define AXIS_TUSER_WIDTH 1

`endif
  