// Auto-generated by Python
// Generated on: 2026-01-03T23:36:51.034190
`ifndef __PARAMETERS_SVH__
`define __PARAMETERS_SVH__

`define IMG_HEIGHT 512
`define IMG_WIDTH 512

`define AXIS_TDATA_WIDTH 8
`define AXIS_TUSER_WIDTH 1

`endif
  